[package]
name = "meilisearch-sdk"
version = "0.3.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"
description = "Rust wrapper for the MeiliSearch API. MeiliSearch is a powerful, fast, open-source, easy to use and deploy search engine."
license = "MIT"
readme  = "README.md"
repository = "https://github.com/meilisearch/meilisearch-sdk"

[dependencies]
serde_json = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["RequestInit", "Headers", "Window", "Response", "console"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dev-dependencies]
env_logger = "0.7"
tokio = { version = "0.2", features = ["macros"] }
